# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  shopizer-ci:
    docker:
      - image: shopizerecomm/ci:latest
        auth:
          username: shopizerecomm
          password: $DOCKERHUB_PASSWORD  
      
working_directory: /tmp


# Define the jobs we want to run for this project
jobs:
  build:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "shopizer build and test (1)"
      - run:
          name: Run shell script
          command: |
            set -x
            /home/shopizer/tools/shopizer.sh tests
      - persist_to_workspace:
          root: .
          paths:
            - sm-shop/*
      #- run:
      #    name: Install Docker client
      #    command: apk add docker-cli
      #- run: |
      #    ls -al
      #    cd sm-shop
      #    docker build . -t shopizerecomm/shopizer:latest
      #    docker build . -t shopizerecomm/shopizer:latest
  deploy:
    machine: true
    steps:
       - attach_workspace:
          at: .
       # start proprietary DB using private Docker image
       # with credentials stored in the UI
       - run: |
           ls -al
       - run: |
           docker login -u shopizerecomm -p $DOCKERHUB_PASSWORD
       - run: |
           (cd sm-shop && mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=shopizerecomm/shopizer:3.0.0)
       - run: |
           docker push shopizerecomm/shopizer:3.0.0

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
